### ISSUE TITLE
Please provide an installation guide.

### ISSUE THREAD

**Issue by rijans** [plesk/ext-ssh-terminal#4]
I installed using the command 

`plesk bin extension --install-url https://codeload.github.com/plesk/ext-ssh-terminal/zip/master`

But in Plesk, the SSH Terminal page shows nothing

**Comment by xgin** [comment]
The extension is not ready for usage.
It will be available in the extensions catalog, when the project comes to at least beta-stage.

**Comment by rijans** [comment]
Okay
